'use client';
import { Provider } from 'react-redux';
import './globals.css';
import store from './store/store';
import Sidebar from './components/sidebar';
import { usePathname } from 'next/navigation';
// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const pathname = usePathname();

  const isLoginPage = pathname === '/login';
  return (
    <html lang="pt">
      <body className="bg-white" >
        <Provider store={store}>
          {isLoginPage ? (
              // Apenas renderiza o conteúdo sem a sidebar
              <div className="h-screen">{children}</div>
            ) : (
              // Layout com a sidebar
              <div className="flex h-screen">
                <Sidebar />
                <main className="ml-[262px] flex-1 overflow-y-auto p-8">
                  {children}
                </main>
              </div>
            )}
        </Provider>
        </body>
    </html>
  )
}
